# Generated by Django 5.1.6 on 2025-02-17 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("livre", "Livre"),
                            ("dvd", "DVD"),
                            ("cd", "CD"),
                            ("jeu de plateau", "Jeu de plateau"),
                        ],
                        default="livre",
                        max_length=20,
                    ),
                ),
                ("auteur", models.CharField(blank=True, max_length=250, null=True)),
                ("disponible", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Membre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("bloque", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emprunt", models.DateField(auto_now_add=True)),
                ("date_retour", models.DateField(blank=True, null=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliotheque.media",
                    ),
                ),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bibliotheque.membre",
                    ),
                ),
            ],
        ),
    ]
