# Generated by Django 5.1.6 on 2025-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibliotheque", "0002_alter_emprunt_membre"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprunt",
            name="date_retour_effectif",
            field=models.DateField(blank=True, null=True),
        ),
    ]
